ARG MAXWELL_VERSION

# https://www.docker.elastic.co/
FROM zendesk/maxwell:${MAXWELL_VERSION:-latest}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
